### ISSUE TITLE
[Question] Run build

### ISSUE THREAD

**Issue by Nefarem** [Vinorcola/CityBuilderEngine#14]
Starting build-CityBuilderEngine_Qt_5_15_2_MinGW_64_bit-Debug\debug\CityBuilderEngine.exe ...
terminate called after throwing an instance of 'YAML::BadFile'
what(): bad file

When I try run from directory no by compiler I have error about missing "Qt5Widgets.dll", "Qt5Gui.dll" , "Qt5Core.dll"

**Comment by Vinorcola** [comment]
You must configure the running directory as the root directory of the project in QtCreator. By default, QtCreator set the running directory to the compiled directory

**Comment by Nefarem** [comment]
Work, ty.
